### ISSUE TITLE
/depositall cause an exception and doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [Pugabyte/AutomaticInventory#3]
Depositall doesnt work, there is an error showing up: https://pastebin.com/DmX4GbdJ
Anyway the plugin loads correctly and the other feature work.
AutomaticInventory: 2.9
PaperSpigiot 1.12.2 #1402

**Comment by Pugabyte** [comment]
I'm not having this issue. what exact steps are you following to reproduce this? what items are you sorting, etc

**Comment by TheoRetisch1** [comment]
Sorry for the long delay. 
1. I used your download button to get the newest version (https://github.com/Pugabyte/AutomaticInventory).
2. I started the server with the plugin using PaperSpigiot 1.12.2 #1463, without any errors during the startup: `https://github.com/Pugabyte/AutomaticInventory`
3. Every function except depositall works perfectly fine
4. If one enter the command /depositall all he or she will get the following error and nothing will happen: ```
[18:05:50] [Server thread/INFO]: TheoRetisch1 issued server command: /depositall
[18:05:51] [Server thread/WARN]: [AutomaticInventory] Task #57360 for AutomaticInventory v2.9 generated an exception
java.lang.NullPointerException: null
	at me.pugabyte.automaticinventory.AutomaticInventory.depositMatching(AutomaticInventory.java:124) ~[AutomaticInventory.jar:?]
	at me.pugabyte.automaticinventory.FindChestsThread$QuickDepositChain.run(FindChestsThread.java:191) ~[AutomaticInventory.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1463]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1463]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1463]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```
I tried to sort lots of stuff: potions, blocks, items nothing worked. So as a test just try to sort grass.

The error doesn't appear if you use the orginal version of the plugin. Something must have went wrong when you updated the plugin 23 days ago. Unfortunatly I dont have an old version of your fork so I can't prove that the error is related to the lastest version, but as I never had problems before I would strongly suspect this.

**Comment by Pugabyte** [comment]
Can you do me a favor and test this on Spigot 1.12.2? I still haven't run into this issue on my server

**Comment by Pugabyte** [comment]
Interesting. Try hitting the download button again, I replaced the jar with the exact one that I have running on my server. I don't know if they were different.

**Comment by TheoRetisch1** [comment]
Yoooo the new jar works perfectly fine! Also the differentiation between potion types is just awesome! Thank you really much :)
